language: erlang

otp_release:
- 17.1
#- 17.0
#- R16B03-1
#- R16B03
#- R16B02
#- R16B01

before_install:
  - sudo apt-get install libssl-dev libxml2-dev libexpat1-dev
  
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jean.parpaillon@lizenn.com
  password:
    secure: bHHqklpkTaBxBV8Bo9hqqLb8QTVbYH2/dBGQ2WxaZDVC4srrsn1R3jDKbq+4Rm1L4lf4jh1uEMWOGbzk8H+WFZNdaxHP7e3mzNIruUinPSMMXYN7pwJZHCjiYPAbSO8Dt+J4UtsGFBJhsmAhOp96iaOzP2IDcbDhmWq7ViB4UEM=
  organization: icare
  space: development
